### ISSUE TITLE
Sum of "% in last election" over 100%

### ISSUE THREAD

**Issue by andr444** [orbs-network/orbs-ethereum-contracts#106]
**Describe the bug**

Sum of "% in last election" over 100%

**Steps To Reproduce**

1. Go to https://orbs-network.github.io/voting/delegator
4. See error - in "% in last election" 

**Expected behavior**

Sum of "% in last election" should be 100%

**Logs**

If applicable, provide the link to the log files that contain the issue.

**Screenshots**

**Environment:**

If applicable, add the information about that you are running and their versions

**Additional context**

If possible, provide the failing test the reveals the issue.

**Comment by gilamran** [comment]
Done
