### ISSUE TITLE
Add "%" to column values

### ISSUE THREAD

**Issue by andr444** [orbs-network/orbs-ethereum-contracts#107]
**Is your feature request related to a problem? Please describe.**
People are confused by "Last election votes against (%)" column

A clear and concise description of what the problem is. E.g, I'm always frustrated when [...]

**Describe the solution you'd like**
In the last column on https://orbs-network.github.io/voting/guardian page add "%" to the values displayed in the column

A clear and concise description of what you want to happen. If applicable, consider adding a code example of how you'd like to use the feature.

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered. If applicable, provide links to alternative solutions/features in other projects.

**Additional context**

**Comment by gilamran** [comment]
Done
