### ISSUE TITLE
Add "Already distributed" value

### ISSUE THREAD

**Issue by andr444** [orbs-network/orbs-ethereum-contracts#108]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. E.g, I'm always frustrated when [...]

**Describe the solution you'd like**
On the rewards page at https://orbs-network.github.io/voting/reward add a value called "Received rewards" with the sum of all rewards this address received so far.

A clear and concise description of what you want to happen. If applicable, consider adding a code example of how you'd like to use the feature.

**Describe alternatives you've considered**

A clear and concise description of any alternative solutions or features you've considered. If applicable, provide links to alternative solutions/features in other projects.

**Additional context**

**Comment by gilamran** [comment]
@andr444 I don't remember the reason for this task. Do you?

**Comment by andr444** [comment]
Solved with "Total Distributed", no further issue here
