### ISSUE TITLE
Incorrect Validators balance

### ISSUE THREAD

**Issue by andr444** [orbs-network/orbs-ethereum-contracts#121]
**Describe the bug**
https://orbs-network.github.io/voting/validator
The balance is incorrect, showing 0 for addresses that just received rewards

**Steps To Reproduce**

1. Go to https://orbs-network.github.io/voting/validator
2. See balance

**Expected behavior**
Show correct, up-to-date Validators balance

**Logs**

If applicable, provide the link to the log files that contain the issue.

**Screenshots**

**Environment:**

If applicable, add the information about that you are running and their versions

**Additional context**

If possible, provide the failing test the reveals the issue.

**Comment by gilamran** [comment]
@andr444 Still relevant?

**Comment by andr444** [comment]
Nope, all seems fine now
Thanks!
