### ISSUE TITLE
Change "None-Delegated" to "Not delegated"

### ISSUE THREAD

**Issue by andr444** [orbs-network/orbs-ethereum-contracts#135]
**Describe the bug**

Seems to be a misspelling of the term
Change "None-Delegated" to "Not delegated" in this project

**Steps To Reproduce**

**Expected behavior**

**Logs**

If applicable, provide the link to the log files that contain the issue.

**Screenshots**

**Environment:**

If applicable, add the information about that you are running and their versions

**Additional context**

If possible, provide the failing test the reveals the issue.

**Comment by gilamran** [comment]
Fixed
