### ISSUE TITLE
An error in "Delegation details" - unrefreshed erroneous fields

### ISSUE THREAD

**Issue by andr444** [orbs-network/orbs-ethereum-contracts#136]
**Describe the bug**

When checking an address that delegates, then checking an address that doesn't, some of the fields in "Delegation Details" do not refresh
The fields are:
* Guardian voted in previous elections
* Guardian voted for next elections	

Another issue - for the address 0x86b234a86d57E707fBE1A406780941FDaB6690A5 these fields are empty, though the address delegates to a valid Guardian

**Steps To Reproduce**

1. Go to "https://orbs-network.github.io/voting/reward"
2. Input a delegating address - such as 0x6dda3D258e21Abc37668E82aE543e8C77567F220
3. Scroll down to Delegation Details
4. See the fields populated with green YES
5. Input a non-delegating address - such as 
0xD5C78e498A1BF8d3fb88BA9a2dD71f6931c590D0
6. The fields are still populated with YES, though there is no delegation. Should be blank

**Expected behavior**

All fields should update according to the correct information

**Logs**

If applicable, provide the link to the log files that contain the issue.

**Screenshots**

**Environment:**

If applicable, add the information about that you are running and their versions

**Additional context**

If possible, provide the failing test the reveals the issue.

**Comment by gilamran** [comment]
Fixed:
Now, in case of "Not-Delegated" I'm disabling (Showing`-`) all the other fields.
