### ISSUE TITLE
Validator stakes missing commas

### ISSUE THREAD

**Issue by andr444** [orbs-network/orbs-ethereum-contracts#143]
**Describe the bug**
On https://orbs-network.github.io/voting/validator there should be commas in the Validator stakes, such as "4,344,593 ORBS" instead of "4344593 ORBS"
Also, to shorten the column, change column title to "Stake (in ORBS)" and drop the word "ORBS" from the cells, leaving just the number (with commas)

**Steps To Reproduce**

**Expected behavior**

**Logs**

If applicable, provide the link to the log files that contain the issue.

**Screenshots**

**Environment:**

If applicable, add the information about that you are running and their versions

**Additional context**

If possible, provide the failing test the reveals the issue.

**Comment by gilamran** [comment]
Fixed
