### ISSUE TITLE
Display delegation info next to rewards

### ISSUE THREAD

**Issue by bolshchikov** [orbs-network/orbs-ethereum-contracts#87]
**Is your feature request related to a problem? Please describe.**

Users would like to see all relevant information in one place regarding rewards. Providing info about just rewards is not enough, it should be put in the context.

**Describe the solution you'd like**

We propose to add one more table below rewards table with the following information:

---
### Delegation Details
| | |
|-----|----------|
|Delegated to|`0x12345678910121314`|
|Delegator's Orbs Balance|1234|
|Voted in previous elections|Yes/No|
|Voted for next elections|Yes/No|

---

**Comment by andr444** [comment]
This is an important feature! 
I suggest the following format:

## Delegation details

  |  
-- | --
Delegated to | 0x12345678910121314
Delegator's Orbs Balance | 1234
Voted in previous elections | Yes/No
Voted for next elections | Yes/No
Delegation block number | [Ethereum block number]
Delegation method | [Delegate / Transfer]
Delegation timestamp | [Time in human-readable format]

**Comment by bolshchikov** [comment]
@andr444 , then it will make sense to display similar information in the delegation status popup under on the `Guardians` page?

**Comment by andr444** [comment]
Yes, makes sense

**Comment by bolshchikov** [comment]
If delegation is performed thru `Delegate`actions => read `delegate` event from Ethereum and extract the timestamp from there.
